---
# tasks file for consul
# - name: Create List of nodes to be added into Cluster
- name: Create List of nodes to be added into Cluster
  set_fact: NODELIST={%for host in groups['consul_server']%}"{{hostvars[host].ansible_eth0.ipv4.address}}"{% if not loop.last %},{% endif %}{% endfor %}

- name: Unarchive a file that needs to be downloaded and copy to path
  unarchive:
    src: https://releases.hashicorp.com/consul/0.9.2/consul_0.9.2_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: yes
  register: result
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Create a directory if it does not exist
  file:
    path: /etc/consul.d/
    state: directory
    mode: '0755'
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Configure consul
  template:
    src: config-json.j2
    dest: /etc/consul.d/config.json
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart-consul
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Copy consul Systemd
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart-consul
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Start service consul, if not started
  service:
    name: consul
    state: started
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Enable service consul, and not touch the state
  service:
    name: consul
    enabled: yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
