---
# tasks file for memcached_exporter

- name: Install epel Repo
  yum:
    name: epel-release
    state: present
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Unarchive a file that needs to be downloaded
  unarchive:
    src: https://github.com/prometheus/memcached_exporter/releases/download/v0.6.0/memcached_exporter-0.6.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes
  register: result
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Copy memcached_exporter binary to PATH
  copy:
    src: /tmp/memcached_exporter-0.6.0.linux-amd64/memcached_exporter
    dest: /usr/local/bin/memcached_exporter
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Copy memcached_exporter Systemd
  copy:
    src: memcached_exporter.service
    dest: /etc/systemd/system/memcached_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart-memcached-exporter
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Start service memcached exporter, if not started
  service:
    name: memcached_exporter
    state: started
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Enable service memcached exporter, and not touch the state
  service:
    name: memcached_exporter
    enabled: yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
