---
  - name: Redis Exporter Configuration
    hosts: all
    become: yes
    become_user: root
    remote_user: hrishikesh
    roles:
      - { role: iptables }
      - { role: packages }
      - { role: redis_exporter }
    handlers:
    - name: restart-redis-exporter
      service:
        name: redis_exporter
        state: restarted
    vars:
      REDIS_PASSWORD: PASSWORD
      CLUSTER_MODE: true