---
  - name: Node Exporter Configuration
    hosts: all
    become: yes
    become_user: root
    remote_user: hrishikesh
    roles:
      - { role: iptables }
      - { role: packages }
      - { role: node_exporter }
    handlers:
    - name: restart-node-exporter
      service:
        name: node_exporter
        state: restarted
