---
  - name: Rabbitmq Server Configuration
    hosts: all
    become: yes
    become_user: root
    remote_user: hrishikesh
    roles:
      - { role: iptables }
      - { role: packages }
      - { role: rabbitmq }
    handlers:
    - name: restart-rabbitmq
      service:
        name: rabbitmq-server
        state: restarted
    vars:
      ADMIN_USER: USERNAME
      ADMIN_PASSWORD: PASSWORD
